name: Merge Feature Branches to Develop

on:
  push:
    branches:
      - 'feature/*'  

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: develop 
          head: ${{ github.ref }} 
          title: "Merge feature branch to develop"
          body: "This is an automated PR to merge the feature branch into develop"
          draft: false 
